wechat_id: HomePi#replace this with your wechat id
help_message: 欢迎关注H@mePi！智能生活，尽在H@mePi！
welcome_message:
  title: H@mePI
  picture: https://mp.weixin.qq.com/cgi-bin/getimgdata?token=1505676036&msgid={msgid}&mode=large&source=file&fileId=200024723&ow=-1 
  description: 欢迎您关注H@mePi
  link: http://mp.weixin.qq.com/wiki/index.php
